# https://github.com/matomo-org/docker/blob/master/.examples/apache/docker-compose.yml
version: "3"

services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: miriha/multi-route:0.1
    restart: always
    command: "uvicorn app.main:app --host 0.0.0.0 --port 80 --reload"
    volumes:
      - ./app:/code/app
    environment:
      - ENV_VAR=first
    ports:
      - 8090:80